version: "3"
services:

  mongo:
    image: mongo
    volumes:
      - ./db:/data/db

  server:
    build:
      context: ./server
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      - mongo

  oracle:
    build:
      context: ./server
    env_file:
      - .env
    depends_on:
      - mongo
    command: "node oracle.js"
