version: "3"
services:

  bet_oracle:
    build:
      context: ./bet_oracle_docker
    hostname: "bet_oracle"
    ports:
      - "8080:80"

  #ethereum:
  #  build:
  #    context: ./ethereum_docker
  #  hostname: "ethereum"
  #  ports:
  #    - "30303:30303"
  #    - "30303:30303/udp"
  #    - "8545:8545"
  #  entrypoint: "/root/start.sh"
  #  command: '--chain kovan --rpccorsdomain="*" --rpc'

  ethereum:
    image: parity/parity:v1.7.0
    hostname: "ethereum"
    ports:
      - "8180:8180"
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    command: "--chain kovan --ui-interface all --jsonrpc-interface all --ws-interface all --ws-origins all"