version: "3"
services:

  mongo:
    image: mongo
    volumes:
      - ./db:/data/db

  server:
    build:
      context: ./server
    hostname: "bet_oracle"
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      - mongo